application: carter-lasa-blog-log2
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /img
  static_dir: images
- url: /.*
  script: lasanfound.application


